---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  container-image:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Derive tags
        run: |
          echo 'tags<<EOF' >> $GITHUB_ENV
          if [[ "${{ github.ref_type }}" == 'tag' ]]; then
            echo "latest ${{ github.ref_name }} ${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "${{ github.ref_name }} ${{ github.sha }}" >> $GITHUB_ENV
          fi
          echo 'EOF' >> $GITHUB_ENV

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: esp-rs-distrobox
          tags: "${{ env.tags }}"
          containerfiles: Containerfile
          oci: true

      - name: Push image to GHCR
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/dannixon
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

